dataset_name: pascal_voc
exp_dir: ./experiments
train_dataset_dir: /home/tony/Documents/datasets/sbd_dataset
test_dataset_dir: /home/tony/Documents/datasets/VOC2012
train_name: train.txt
test_name: val.txt
num_classes: 21
type1: sbd
type2: voc
train_model: model2
ckpt_dir: checkpoint3
reload_skip_model: True
reload_dir: checkpoint2
reload_ckpt_file: fcn32s_bp_120000
continue_train: True
init_checkpoint_file: fcn16s_bp_116000
log_dir: logs3
batch_size: 5
test_batch_size: 4
average_gradients: 4
train_model: model2
global_step: 0
start_step: 0
epochs: 175
summary_freq: 100
testing_freq: 4000
l_rate_decay_epoch: 25
l2: 0.0005
l_rate: 0.0001
print_every: 5

