dataset_name: pascal_voc
exp_dir: ./experiments
test_dataset_dir: /home/tony/Documents/datasets/VOC2012
test_name: seg11valid.txt
num_classes: 21
type2: voc
train_model: model3
ckpt_dir: checkpoint4
continue_train: True
init_checkpoint_file: fcn8s_bp_204000
test_batch_size: 1
global_step: 2040000
print_every: 5
